name: lint

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: sudo apt-get update -qq && sudo apt-get install -y -qq libxml2-utils

      - name: 静态检查
        run: ./lint.sh
